# docker build --rm -t oe_how -f Dockerfile.how .
# docker run -d -it -p 5000:5000 --name oe_how oe_how
FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y build-essential
RUN apt-get install -y python-dev      \
    python-pip      \
    vim             \
    python          \
    iputils-ping    \
    net-tools
RUN pip install --upgrade pip
RUN pip install flask
COPY ./vimrc /etc/vim
EXPOSE 5000

RUN mkdir -p /home/root/how
WORKDIR /home/root/how


